### ISSUE TITLE
机器人快速创建、删除HOOK引发的问题

### ISSUE THREAD

**Issue by shakugannosaints** [Cola-Ace/koishi-plugin-bridge-discord-qq#1]
![8c985293053e32aa63abd20637f0b771](https://github.com/user-attachments/assets/3a635094-d755-4f52-be08-4d04840bfd04)
由于实现中不停创建、删除HOOK，消息到达一定频率后，dc会因为“删除hook速度过快”而限制hook删除。此时hook会堆积到满，然后机器人就不能再发送消息了。
我的环境：本机部署的机器人（非服务器）

**Comment by Cola-Ace** [comment]
那我晚点改成在机器人启动时就固定使用一个webhook，不再对webhook频繁实现创建和删除，应该能解决你的问题

**Comment by Cola-Ace** [comment]
我看看能不能针对webhook删除失败的错误进行等待后再次重试

**Comment by Cola-Ace** [comment]
另外，在我自己的服务器上，消息频率不会太高，所以我选择了webhook发送消息以实现沉浸式消息互通，所以如果你的qq群发送消息的频率超过30条消息/分钟的话，那么这个插件不太适合你，因为discord本身就有针对webhook的30条消息/分钟的频率限制，你可能需要寻找其他不使用webhook的插件以满足你的需求

**Comment by Cola-Ace** [comment]
我在1.3.1版本中修改了一下webhook的机制，现在程序会先判断当前频道是否有由bot创建的webhook并调用该webhook，没有的话会创建一个webhook，调用后删除。同时，由于我发现在我自己的服务器上测试时，koishi发送一次消息后会创建一个当前频道的webhook并且不会删除（如果已经创建过的话则不会再次创建），所以如果无误的话后续都会调用名为Koishi的webhook发送消息（或者其他由bot创建的webhook，取决于bot获取webhooks列表的顺序）。如果koishi不会自动创建webhook的话那么程序的逻辑会和旧版一样，所以你有可能再次遇到你所描述的问题。如果你的koishi不会自动创建webhook的话请回复我，我会再次尝试修复这个问题
