### ISSUE TITLE
使用@everyone等非單一用戶的@、用戶未設置頭像會發生錯誤

### ISSUE THREAD

**Issue by pxperson** [Cola-Ace/koishi-plugin-bridge-discord-qq#4]
` Error: Error with request send_group_msg, args: {"group_id":xxxxxxxxxx,"message":[{"type":"image","data":{"file":"null?size=64","cache":0}},{"type":"text","data":{"text":"[Discord] xxxx:\nxxxxxxxxx"}}]}, retcode: 1200
                            at _Internal._get (C:\Users\USER\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (C:\Users\USER\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:162:20)
                            at async OneBotMessageEncoder.flush (C:\Users\USER\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:763:330)
                            at async OneBotMessageEncoder.send (C:\Users\USER\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:681:5)
                            at async Proxy.sendMessage (C:\Users\USER\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:411:22)
                            at async Proxy.<anonymous> (C:\Users\USER\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-bridge-qq-discord\lib\index.js:623:38)`

`
{"id":2280,"type":"info","level":2,"name":"bridge","meta":{},"content":"-------Message-------","timestamp":1734860345882}
{"id":2281,"type":"info","level":2,"name":"bridge","meta":{},"content":"{ messageId: \u001b[32m'1320324733786521633'\u001b[39m, id: \u001b[32m'1320324733786521633'\u001b[39m, content: \u001b[32m'<at type=\"all\"/>'\u001b[39m, elements: [ Element { type: \u001b[32m'at'\u001b[39m, attrs: { type: \u001b[32m'all'\u001b[39m }, children: [] } ], createdAt: \u001b[33m1734860346982\u001b[39m, updatedAt: \u001b[1mnull\u001b[22m }","timestamp":1734860345884}
{"id":2282,"type":"info","level":2,"name":"bridge","meta":{},"content":"-------Sender-------","timestamp":1734860345885}
{"id":2283,"type":"info","level":2,"name":"bridge","meta":{},"content":"{ id: \u001b[32m'xxxxxxxxxxxxxxxxxxx'\u001b[39m, nick: \u001b[32m'xxxxx'\u001b[39m, name: \u001b[32m'xxxxxx'\u001b[39m, userId: \u001b[32m'xxxxxxxxxxxxxxxxxx'\u001b[39m, avatar: \u001b[32m'https://cdn.discordapp.com/avatars/xxxxxxxxxxxxx/xxxxxx.png'\u001b[39m, username: \u001b[32m'xxxxxxxx'\u001b[39m, discriminator: \u001b[32m'0'\u001b[39m, isBot: \u001b[33mfalse\u001b[39m }","timestamp":1734860345885}
{"id":2284,"type":"info","level":2,"name":"bridge","meta":{},"content":"-------End--------","timestamp":1734860345885}
{"id":2294,"type":"error","level":1,"name":"bridge","meta":{},"content":"Error: [400] {\"message\":\"Invalid Form Body\",\"code\":50035,\"errors\":{\"user_id\":{\"_errors\":[{\"code\":\"NUMBER_TYPE_COERCE\",\"message\":\"Value \\\"undefined\\\" is not snowflake.\"}]}}}\n    at _Internal.<computed> [as getUser] (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@satorijs\\adapter-discord\\lib\\index.cjs:125:21)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Proxy.<anonymous> (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\koishi-plugin-bridge-qq-discord\\lib\\index.js:583:39)","timestamp":1734860346432}
` 
`
{"id":2299,"type":"info","level":2,"name":"bridge","meta":{},"content":"-------Message-------","timestamp":1734860404640}
{"id":2300,"type":"info","level":2,"name":"bridge","meta":{},"content":"{ messageId: \u001b[32m'xxxxxxxxx'\u001b[39m, id: \u001b[32m'xxxxxxxxx'\u001b[39m, elements: [ Element { type: \u001b[32m'at'\u001b[39m, attrs: { type: \u001b[32m'all'\u001b[39m }, children: [] }, Element { type: \u001b[32m'text'\u001b[39m, attrs: { content: \u001b[32m' '\u001b[39m }, children: [] } ], content: \u001b[32m'<at type=\"all\"/> '\u001b[39m }","timestamp":1734860404641}
{"id":2301,"type":"info","level":2,"name":"bridge","meta":{},"content":"-------Sender-------","timestamp":1734860404642}
{"id":2302,"type":"info","level":2,"name":"bridge","meta":{},"content":"{ id: \u001b[32m'xxxxxxxxxxx'\u001b[39m, name: \u001b[32m'xxxxx'\u001b[39m, userId: \u001b[32m'xxxxxxxxxxx'\u001b[39m, avatar: \u001b[32m'http://q.qlogo.cn/headimg_dl?dst_uin=xxxxxxxxxx&spec=640'\u001b[39m, username: \u001b[32m'xxxxxx'\u001b[39m }","timestamp":1734860404643}
{"id":2303,"type":"info","level":2,"name":"bridge","meta":{},"content":"-------End--------","timestamp":1734860404643}
{"id":2304,"type":"error","level":1,"name":"bridge","meta":{},"content":"TypeError: Cannot read properties of undefined (reading 'indexOf')\n    at ProcessorQQ.at (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\koishi-plugin-bridge-qq-discord\\lib\\index.js:148:37)\n    at ProcessorQQ.process (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\koishi-plugin-bridge-qq-discord\\lib\\index.js:100:45)\n    at Proxy.<anonymous> (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\koishi-plugin-bridge-qq-discord\\lib\\index.js:419:58)\n    at Object.apply (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@cordisjs\\core\\lib\\index.cjs:417:23)\n    at Proxy.dispatch (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@cordisjs\\core\\lib\\index.cjs:514:27)\n    at dispatch.next (<anonymous>)\n    at Function.from (<anonymous>)\n    at Proxy.emit (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@cordisjs\\core\\lib\\index.cjs:521:11)\n    at OneBotBot.dispatch (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@satorijs\\core\\lib\\index.cjs:403:20)\n    at dispatchSession (C:\\Users\\USER\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\koishi-plugin-adapter-onebot\\lib\\index.js:402:7)","timestamp":1734860404646}`

**Comment by Cola-Ace** [comment]
该问题已在 v1.6.9 修复
